
services:

  pi-cam-camera:
    build: ./USBCameraApp
    restart: always
    devices:
      - "/dev/video0:/dev/video0"
    environment:
      CAMERA_DEVICE: "/dev/video0"
      STREAM_PORT: 8000
      CONTROLLER_URL: "http://pi-cam-controller:8001"

  pi-cam-controller:
    build: ./CameraController
    restart: always
    depends_on:
      - pi-cam-camera
      - pi-cam-database
    environment:
      CAMERA_API_URL: "/api"
      DATABASE_URL: "postgres://camuser:securepass@pi-cam-database:5432/camdb"
      CAMERA_SERVICE_URL: "http://pi-cam-camera:8000"
    expose:
      - "8001"
    volumes:
      - media_data:/app/media
      - static_data:/app/static

  pi-cam-nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - static_data:/app/static:ro
      - media_data:/app/media:ro
    depends_on:
      - pi-cam-controller
      - pi-cam-camera

  pi-cam-database:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: camdb
      POSTGRES_USER: camuser
      POSTGRES_PASSWORD: securepass
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  media_data:
  static_data:
