
services:

  pi-cam-camera:
    build: ./USBCameraApp
    restart: always
    # devices:
      #  - "/dev/video0:/dev/video0"
    env_file:
      - ./.env
    environment:
      STREAM_PORT: 8000
      CONTROLLER_URL: "http://pi-cam-controller:8001"

  pi-cam-controller:
    build: ./CameraController
    restart: always
    depends_on:
      - pi-cam-camera
      - pi-cam-database
    env_file:
      - ./.env
    environment:
      DATABASE_URL: "postgres://camuser:securepass@pi-cam-database:5432/camdb"
      CAMERA_SERVICE_URL: "http://pi-cam-camera:8000"
    expose:
      - "8001"
    volumes:
      - media_data:/app/media
      - static_data:/app/static

  pi-cam-nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./.env
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - static_data:/app/static:ro 
      - media_data:/app/media:ro
    depends_on:
      - pi-cam-controller
      - pi-cam-camera
    entrypoint: ["sh","-c","sleep 10 && nginx -g 'daemon off;'"]

  pi-cam-database:
    image: postgres:14-alpine
    restart: always
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  media_data:
  static_data:
