# Generated by Django 4.2 on 2025-04-29 00:00
from django.db import migrations, models
import django.core.validators

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # no dependencies or you can list other app migrations here
    ]

    operations = [
        migrations.CreateModel(
            name='CameraSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brightness', models.IntegerField(default=128, help_text='0–255, mid-point brightness')),
                ('contrast', models.IntegerField(default=64, help_text='0–255, moderate contrast')),
                ('saturation', models.IntegerField(default=64, help_text='0–255, moderate saturation')),
                ('hue', models.IntegerField(default=0, help_text='0–180, default hue')),
                ('gain', models.IntegerField(default=0, help_text='0–255, default gain (off)')),
                ('auto_exposure', models.BooleanField(default=True, help_text='Enable automatic exposure (V4L2)')),
                ('manual_exposure', models.IntegerField(default=-6, help_text='Manual exposure value (V4L2): range -13 (slow) to 0 (fast)', validators=[django.core.validators.MinValueValidator(-13), django.core.validators.MaxValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Camera Settings',
                'verbose_name_plural': 'Camera Settings',
            },
        ),
    ]
